steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t gcr.io/$PROJECT_ID/palm2-chat-app:${SHORT_SHA} .
  automapSubstitutions: true
images:
- 'gcr.io/$PROJECT_ID/palm2-chat-app'

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy cloudrunservice --image gcr.io/$PROJECT_ID/palm2-chat-app:${SHORT_SHA} --region us-central1 --platform managed --allow-unauthenticated
  automapSubstitutions: true
